name: print hello and goodbye
on: [workflow_dispatch,push]
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi was geht"
      - name: Say bye bye
        run: echo "Funktioniert. Bye bye"     