name: TEST FLUTTER APP
on: [workflow_dispatch,push]
  
env:
  FLUTTER_VERSION: "3.0.5"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b $FLUTTER_VERSION _flutter
      - name: makea clean
        run: flutter clean
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Flutter Analyze
        run: flutter analyze
      - name: Run Flutter Tests
        run: flutter test